### ISSUE TITLE
Implement option to disable opening of new lightbox when one is already open

### ISSUE THREAD

**Issue by warpling** [jsor/lity#142]

**Comment by jsor** [comment]
There's no built-in method for that. This most simple solution would be

```css
.lity-active [data-lity] {
    pointer-events: none;
}
```
