### ISSUE TITLE
A bit of spacing around the image?

### ISSUE THREAD

**Issue by jjnxpct** [jsor/lity#145]
What would be the best way to create a bit of spacing around the image in the lightbox? So it won't be all the way to the top/bottom of the browser window?

**Comment by jsor** [comment]
What about

```css
.lity-image img {
    padding: 20px;
}
```
