### ISSUE TITLE
Is background scroll a feature of a bug?

### ISSUE THREAD

**Issue by johanson** [jsor/lity#3]
If you open lity, the background is still scrollable. 

The lity container is not of course, but if you open lity on mobile and try to zoom the picture, it sometimes get's difficult because of the scrollable body.

Currently I'm just hooking body -> overflow: hidden on open and body -> overflow: auto on close.

Is that something you're maybe interested in adding to the project itself?

**Comment by jsor** [comment]
This is more like a feature. Since i want to keep lity lightweight, i didn't implemented it. You need to implement that by yourself exactly how you did it.

**Comment by jsor** [comment]
I've release the new version 1.4.0 which now toggles a `lity-active` class on the `<html>` element.

Simply add

```css
.lity-active,
.lity-active body {
    overflow: hidden;
}
```

if you want a non-scrollable body while lity is opened.

You could even improve this (eg. in combination with Modernizr) and only make the body non-scrollable on touch devices:

```css
.lity-active.touch,
.lity-active.touch body {
    overflow: hidden;
}
```
