### ISSUE TITLE
window size

### ISSUE THREAD

**Issue by biju001** [jsor/lity#35]
is there any way to set window size. example i want change my iframe window size 640x480 then how ?

**Comment by jsor** [comment]
Overwriting the following CSS should do the trick:

```css
.lity-iframe .lity-container {
  max-width: 640px;
}
.lity-iframe-container {
  padding-top: 75%; /* 4:3 ratio */
}
```
